baseURL: 'https://www.dubeg.ca/'
languageCode: en-us
title: DUBE.G
pluralizelisttitles: false
disablePathToLower: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 4
outputs:
  home:
  - HTML
  - JSON
markup:
  goldmark:
    renderer:
      unsafe: true