baseURL: 'https://dubeg.ca/'
languageCode: en-us
title: DUBE.G
pluralizelisttitles: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 4